### ISSUE TITLE
TypeError: relu(): argument must be Tensor, not NoneType

### ISSUE THREAD

**Issue by XunShao-02** [ShenZheng2000/MATH_32_HW2#3]
<img width="1069" alt="截屏2023-06-27 20 59 45" src="https://github.com/ShenZheng2000/MATH_32_HW2/assets/137521211/b51907bb-a50c-4c16-80ac-c2576fe8fe8f">
When I run the $ bash run.sh, it always shows that TypeError: relu(): argument 'input' (position 1) must be Tensor, not NoneType, but I don't change anything to the code.

**Comment by ShenZheng2000** [comment]
You have to first complete all codes in `style_and_content.py`. After that, you will should have the correct Tensor as input.

**Comment by XunShao-02** [comment]
<img width="1069" alt="截屏2023-06-28 21 28 59" src="https://github.com/ShenZheng2000/MATH_32_HW2/assets/137521211/9669c7c4-dd76-442e-97e4-9378a5f4cbd0">

I completed all codes in `style_and_content.py`. After that, I run `bash run.sh` as the instruction said. However, I also face the *Runtime Error* that was mentioned to me that *non-empty 3D or 4D (batch mode) tensor expected for input*.

**Comment by ShenZheng2000** [comment]
You runtime error is due to the incorrect return value of your `class ContentLoss(nn.Module)` and `class StyleLoss(nn.Module)`. Yiling has met the same [issue](https://github.com/ShenZheng2000/MATH_32_HW2/issues/1), and she solved it with the correct return. 

Note that the layers for content and style loss are inserted into the network to calculate the losses at those points. These layers don't modify the data passing through them: they only compute and store the loss.
