### ISSUE TITLE
No reaction

### ISSUE THREAD

**Issue by lifeisbe** [ShenZheng2000/MATH_32_HW2#4]
<img width="777" alt="image" src="https://github.com/ShenZheng2000/MATH_32_HW2/assets/129704270/80deec9b-c959-4f39-8b18-25621d121cf3">
There is no reaction after I insert this command

**Comment by ShenZheng2000** [comment]
1. Double-check the indentation of your shell file, particularly for the "run_main" lines. They should start from the left end.

2. Confirm the proper installation of git by creating a basic shell script that verifies its output.

3. Since style transfer typically consumes a significant amount of time, it is recommended to execute the command line instructions one by one instead of running them all together.
